server:
  port: 8020
spring:
  application:
    name: config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# \u6CE8\u518C\u5230consul\u7684\u670D\u52A1\u540D\u79F0
    config:
      label: master  # git\u4ED3\u5E93\u5206\u652F
      server:
        git:
          uri: https://github.com/missyangxuan/spring-cloud-demo.git  # \u914D\u7F6Egit\u4ED3\u5E93\u7684\u5730\u5740
          search-paths: config-repo  # git\u4ED3\u5E93\u5730\u5740\u4E0B\u7684\u76F8\u5BF9\u5730\u5740\uFF0C\u53EF\u4EE5\u914D\u7F6E\u591A\u4E2A\uFF0C\u7528,\u5206\u5272\u3002
          username: missyangxuan  # git\u4ED3\u5E93\u7684\u8D26\u53F7
          password: yx19940911  # git\u4ED3\u5E93\u7684\u5BC6\u7801
management:
  endpoints:
    web:
      exposure:
        include: "*"