server:
  port: 8020
spring:
  application:
    name: mango-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"
