server:
  port: 8005
spring:
  application:
    name: consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  zipkin:
    base-url: "http://localhost:9411/"
    sleuth:
      sampler:
        probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
feign:
  hystrix:
    enabled: true
